health_icu: Fix error when update from ghis 4.4
  File "/home/feng/gnuhealth/tryton/server/trytond-7.0.29/trytond/model/modelstorage.py", line 1352, in validate_relation_domain
    raise DomainValidationError(
        msg, domain=(invalid_domain, field_def))
trytond.model.modelstorage.DomainValidationError: The value "form" for field "View Type" in "gnuhealth.patient.rounding (gnuhealth.patient.rounding (Form))" of "View" is not valid according to its domain. -