health_lab: Fix report error when no request or analysis date.
    if value.tzinfo is None:
       ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'tzinfo'